import Head from 'next/head' 
import styles from '../styles/Home.module.css' 
import Nav from './components/Nav'
import React , {useEffect, useState} from 'react' 
import Papa from "papaparse";
const allowedExtensions = ["csv"];

export default function Home() {  
    const [error, setError] = useState("");
    const [data, setData] = useState([]);
    const [file, setFile] = useState("");

    useEffect(()=>{ 
 
    }, []);

  const handleParse = async() => { 
    if (!file) return setError("Enter a valid file"); 
    const reader = new FileReader(); 
    reader.onload = async ({ target }) => {
      const csv = Papa.parse(target.result, { header: false });
      const parsedData = csv?.data;
      const my_csv_data = [];
      parsedData.forEach((v)=>{
        // v['id'] = v[0];delete v[0];
        // v['login'] = v[1];delete v[1];
        // v['name'] = v[2];delete v[2];
        // v['salary'] = parseInt(v[3]);delete v[3];
        my_csv_data.push({
          id: v[0],
          login: v[1],
          name: v[2],
          salary: parseInt(v[3]) 
        });
      });
      console.log(my_csv_data); 
      try{
        const data = await fetch('/api/employees/upload', {
          method: 'POST',
          headers: {'Content-Type':'application/json'}, 
          body:  JSON.stringify(my_csv_data),
        });
          alert("Uploaded");
      }
      catch(error){
          throw error;
      }
    };
    reader.readAsText(file);
 
  };

  const handleFileChange = (e) => {
		setError(""); 
		if (e.target.files.length) {
			const inputFile = e.target.files[0]; 
      console.log('Size: ',inputFile.size,'KB' );
			if(inputFile.size > 20000){alert('max. 2MB'); return false;}
			const fileExtension = inputFile?.type.split("/")[1];
			if (!allowedExtensions.includes(fileExtension)) {
				setError("Please input a csv file");
				return;
			} 
			setFile(inputFile);
		}
	}; 


  return (
    
    <div className={styles.container}>
      <Head>
        <title>HR Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          HR Web App
        </h1>

        <p className={styles.description}>
          Please Upload .CSV file, max 2MB
        </p>

        <div className={styles.grid}>
          <input type='file' name='myfile' accept=".csv" onChange={handleFileChange} />
          <button onClick={handleParse} className="btn btn-outline-primary">Upload</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://furqanhussain.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Furqan Hussain 
        </a>
      </footer>
    </div>
  )
}
